apiVersion: v1
kind: Service
metadata:
  name: monitoring
spec:
  selector:
    app: prometheus
    component: server
  type:  NodePort
  ports:
    - name:  prom-port
      port:  9090
      targetPort:  9090
      NodePort: 30098
      protocol: TCP