apiVersion: v1
kind: Pod
metadata:
  name: hostnetworkpod
  namespace: hnp
spec:
  containers:
    - name: myapp
      image: ikubernetes/myapp:v7
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
          protocol: TCP
          hostPort: 81
          name: clement
  nodeName: node1
  hostNetwork: true
