apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-redis
  name: deploy-redis
  namespace: alpine-nginxport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-redis
  template:
    metadata:
      labels:
        app: pod-redis
    spec:
      containers:
        - name: redis-container
          image: redis
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/k8s/redis"
              name: redis-datadir
      volumes:
        - name: redis-datadir
          persistentVolumeClaim:
            claimName: redis-datadir-pvc-1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-redis
  name: svc-devops-redis
  namespace: apline-nginxport
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      nodePort: 36379
  selector:
    app: devops-redis
  sessionAffinity: ClusterIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
