---
# 无头服务???
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: alpine-nginxpor
spec:
  selector:
    app: redis
    appCluster: redis-cluster
  ports:
    - name: redis
      port: 6379
      protocol: TCP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-access
  namespace: alpine-nginxpor
spec:
  selector:
    app: redis
    appCluster: redis-cluster
  ports:
    - name: redis
      port: 6379
      protocol: TCP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: alpine-nginxpor
spec:
  selector:
    app: redis
    appCluster: redis-cluster
  ports:
    - name: redis
      port: 6379
      protocol: TCP
  clusterIP: None