apiVersion: v1
kind: Pod
metadata:
  name:  readiness-exec
  app: readiness-exec
spec:
  containers:
    - image:  busybox:latest
      name:  readiness-exec-demo
      args:
        - /bin/sh
        - -c
        - "while true; do rm -f /tmp/ready; sleep 30; touch /tmp/ready; sleep 300; done"
      readinessProbe:
        exec:
          command: ["test","-e","/tmp/ready"]
        initialDelaySeconds: 5
        periodSeconds: 5
    