version: '3'
services:
  php81:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ibaiqiu/php-fpm-nginx:php81-v1.0
    container_name: php81-nginx
    environment:
      - APP_NAME=jc
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/www:/var/www/html
      - /opt/nginx/conf.d/:/etc/nginx/conf.d
  php81-queue:
    #image: ibaiqiu/php-queue:php81-v1.0
    image: ibaiqiu/php-fpm-queue:php81-v1.0
    container_name: php81-queue
    environment:
      - APP_NAME=jc
    volumes:
      - /opt/www:/var/www/html
      - /opt/nginx/conf.d/:/etc/nginx/conf.d
      - /opt/www/command/supervisord/:/etc/supervisord/conf.d/
      - /opt/www/command/rabbitmq/:/opt/www/command/rabbitmq/

  mysqld80:
    image: mysql:8.0.29
    container_name: mysqld80
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/mysqld80_conf.d:/etc/mysql/mysql.conf.d/
      - /opt/mysqld80:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'CfINOq1OJcGkerV'
    ports:
      - "3306:3306"

  redis6:
    image: redis:6.2.7
    container_name: redis6
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/redis/db:/data
      - /opt/redis/conf:/etc/redis/
    ports:
      - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: es_single
    environment:
      - discovery.type=single-node
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    volumes:
      - /opt/elasticsearch/es_log:/var/log
      - /opt/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  nginx:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./localtime:/etc/localtime
      - ./nginx-html:/var/www/html
    ports:
      - "80:80"
      - "443:443"

  rabbitmq:
    image: rabbitmq:3.9.20-management
    container_name: rabbitmq39
    restart: always
    volumes:
    # chown -R 999:999 /opt/rabbitmq
      - /etc/localtime:/etc/localtime
      - /opt/rabbitmq/mq-log:/var/log/rabbitmq
      - /opt/rabbitmq/mq-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456

  portainer:
    image: hub-mirror.c.163.com/6053537/portainer-ce
    container_name: portainer
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
    ports:
      - 8000:8000
      - 8080:9000
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_PLUGINS: "tables-filter tinymce"
    ports:
      - 8080:8080
