apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-demo
  namespace: default
spec:
  replicas: 7
  strategy:
    rollingUpdate:
      maxSurge: 3
  selector:
    matchLabels:
      app: deploy-myapp
  template:
    metadata:
      labels:
        app: deploy-myapp
        release: canary
    spec:
      containers:
      - name: dpc-demo
        image: ikubernetes/myapp:v6
        ports:
        - name: app-http
          containerPort: 80
          protocol: TCP

