version: '3'
services:
  mysqld80:
    image: mysql:8.0.29
    container_name: mysqld80
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /docker/mysqld80_conf.d:/etc/mysql/mysql.conf.d/
      - /var/lib/mysqld80:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - 3308:3306

  mysqld57:
    image: mysql:5.7.38
    container_name: mysqld57
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - /etc/localtime:/etc/localtime
      - /docker/mysqld57_conf.d:/etc/mysql/mysql.conf.d/
      - /var/lib/mysqld57:/var/lib/mysql
    ports:
      - 3305:3306
