version: '3'
services:
  mysql80:
    image: mysql:8.0.30
    container_name: mysql80
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/mysql80/conf.d/my.cnf:/etc/my.cnf
      - /opt/mysql80:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'lspg3TiPAqHNlfO'
    ports:
      - 3308:3306

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_PLUGINS: "tables-filter tinymce"
    network_mode: "host"
    ports:
      - 8080:8080

  mysql57:
    image: mysql:5.7.38
    container_name: mysql57
    environment:
      MYSQL_ROOT_PASSWORD: 'lspg3TiPAqHNlfO'
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/mysql57/conf.d/my.cnf:/etc/my.cnf
      - /opt/mysql57:/var/lib/mysql
    ports:
      - 3305:3306
    networks:
      - dev_environment

# https://cloud.tencent.com/developer/article/1623549 [docker mysql初始化多个sql脚本]
# chmod 644 /opt/mysql80/conf.d/my.cnf
networks:
  dev_environment:
    driver: bridge
