version: '3'
services:
  mysqld80:
    image: mysql:8.0.30
    container_name: mysqld80
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - /docker/mysqld80_conf.d/my.cnf:/etc/my.cnf
      - /opt/mysqld80:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'lspg3TiPAqHNlfO'
    ports:
      - 3308:3306

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_PLUGINS: "tables-filter tinymce"
    network_mode: "host"
    ports:
      - 8080:8080

  mysqld57:
    image: mysql:5.7.38
    container_name: mysqld57
    environment:
      MYSQL_ROOT_PASSWORD: 'lspg3TiPAqHNlfO'
    volumes:
      - /etc/localtime:/etc/localtime
      - /docker/mysqld57_conf.d/my.cnf:/etc/my.cnf
      - /opt/mysqld57:/var/lib/mysql
    ports:
      - 3305:3306
    networks:
      - dev_environment
networks:
  dev_environment:
    driver: bridge