version: "3"
services:
  igpro-app:
    image: registry-harbor.lunaon.net/lunaon/igpro-app:dev
    container_name: igpro-app
    network: dev_environment
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dev_environment"

      - "traefik.http.routers.igpro-app-dev.entrypoints=web"
      - "traefik.http.routers.igpro-app-dev.service=igpro-app-dev"
      - "traefik.http.services.igpro-app-dev.loadbalancer.server.port=80"
      - "traefik.http.routers.igpro-app-dev.rule=Host(`whoami-11.lunaon.net`)"

#      - "traefik.http.routers.inssrv-dev.entrypoints=web"
      - "traefik.http.routers.inssrv-dev.service=inssrv-dev"
      - "traefik.http.services.inssrv-dev.loadbalancer.server.port=80"
      - "traefik.http.routers.inssrv-dev.rule=Host(`inssrv-dev.lunaon.net`)"




docker run  -d 
--name=igpro-app 
--net=base_dev_environment 

-l traefik.enable=true 
-l traefik.docker.network=base_dev_environment 
-l traefik.http.routers.24814.entrypoints=web 
-l traefik.http.routers.24814.service=24814
-l traefik.http.services.24814.loadbalancer.server.port=80 
-l traefik.http.routers.24814.rule=Host(`igpro-dev.lunaon.net`) 


-l traefik.docker.network=base_dev_environment 
-l traefik.http.routers.25089.entrypoints=web 
-l traefik.http.routers.25089.service=25089 
-l traefik.http.services.25089.loadbalancer.server.port=80 
-l traefik.http.routers.25089.rule=Host(`inssrv-dev.lunaon.net`)

registry-harbor.lunaon.net/lunaon/igpro-app:dev