version: "3"
services:
  gitlab:
    # image: gitlab/gitlab-ce:9.0.0-ce.0
    # image: gitlab/gitlab-ce:9.5.10-ce.0
    # image: gitlab/gitlab-ce:10.8.7-ce.0
    # image: gitlab/gitlab-ce:11.3.4-ce.0
    # image: gitlab/gitlab-ce:11.11.8-ce.0
    # image: gitlab/gitlab-ce:12.0.12-ce.0
    # image: gitlab/gitlab-ce:12.1.17-ce.0
    # image: gitlab/gitlab-ce:12.10.14-ce.0
    # image: gitlab/gitlab-ce:13.0.14-ce.0
    # image: gitlab/gitlab-ce:13.1.11-ce.0
    # image: gitlab/gitlab-ce:13.8.8-ce.0
    image: gitlab/gitlab-ce:13.12.15-ce.0
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        nginx['listen_port'] = '80'
        nginx['listen_https'] = false
        registry_nginx['listen_port'] = '80'
        registry_nginx['listen_https'] = false
        gitlab_rails['lfs_enabled'] = true
        gitlab_rails['registry_enabled'] = true
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - 80:80
      - 2222:2222
    volumes:
      - /docker/gitlab/config:/etc/gitlab
      - /docker/gitlab/logs:/var/log/gitlab
      - /docker/gitlab/data:/var/opt/gitlab
      - /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
