# 一键启动的 jump server
version: '2.4'

services:
  core:
    image: jumpserver/core:${VERSION}
    container_name: jms_core
    # 禁用 core 文件
    ulimits:
      core: 0
    restart: always
    tty: true
    command: start web
    env_file:
      - .env
    volumes:
      # - core-conf:/opt/jumpserver/config.yml
      - core-data:/opt/jumpserver/data
      - core-logs:/opt/jumpserver/logs
    healthcheck:
      test: "curl -fsL http://localhost:8080/api/health/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    networks:
      - jms_network
    depends_on:
      - mariadb10
      - redis6

  koko:
    image: jumpserver/koko:${VERSION}
    container_name: jms_koko
    ulimits:
      core: 0
    restart: always
    tty: true
    env_file:
      - .env
    ports:
      - 2222:2222
    volumes:
      # - koko-conf:/opt/koko/config.yml
      - koko-data:/opt/koko/data
    depends_on:
      core:
        condition: service_healthy
    privileged: true
    healthcheck:
      test: "curl -fsL http://localhost:5000/koko/health/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - jms_network

  lion:
    image: jumpserver/lion:${VERSION}
    container_name: jms_lion
    ulimits:
      core: 0
    restart: always
    tty: true
    env_file:
      - .env
    volumes:
      - lion-data:/opt/lion/data
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "curl -fsL http://localhost:8081/lion/health/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - jms_network

  magnus:
    image: jumpserver/magnus:${VERSION}
    container_name: jms_magnus
    ulimits:
      core: 0
    restart: always
    tty: true
    env_file:
      - .env
    ports:
      - ${MAGNUS_MYSQL_PORT:-3306}:33060
      - ${MAGNUS_MARIADB_PORT:-3307}:33061
      - ${MAGNUS_REDIS_PORT:-6379}:63790
    volumes:
      - magnus-data:/opt/magnus/data
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "ps axu | grep -v 'grep' | grep magnus"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - jms_network

  web:
    image: jumpserver/web:${VERSION}
    container_name: jms_web
    ulimits:
      core: 0
    restart: always
    tty: true
    environment:
      USE_IPV6: ${USE_IPV6}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-4096m}
    volumes:
      - /opt/jumpserver/webui/default.conf:/etc/nginx/conf.d/default.conf
      - web-data:/opt/jumpserver/data
      - web-logs:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: "curl -fsL http://localhost/ > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - jms_network

  mariadb10:
    image: jumpserver/mariadb:10.6
    container_name: jms_mysql
    restart: always
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      DB_PORT: $DB_PORT
      MARIADB_ROOT_PASSWORD: $DB_PASSWORD
      MARIADB_DATABASE: $DB_NAME
    volumes:
      # - mariadb10-conf:/etc/mysql/mariadb.cnf
      - mariadb10-data:/var/lib/mysql
    healthcheck:
      test: "mysql -h127.0.0.1 -P$$DB_PORT -uroot -p$$MARIADB_ROOT_PASSWORD -e 'SHOW DATABASES;'"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - jms_network

  redis6:
    image: jumpserver/redis:6.2
    container_name: jms_redis
    restart: always
    command: ["redis-server", "/etc/redis.conf", "--requirepass", "$REDIS_PASSWORD"]
    environment:
      REDIS_PORT: $REDIS_PORT
      REDIS_PASSWORD: $REDIS_PASSWORD
    volumes:
      - redis-data:/data
      - /opt/redis/redis.conf:/etc/redis.conf
    healthcheck:
      test: "redis-cli -h 127.0.0.1 -p $$REDIS_PORT -a $$REDIS_PASSWORD info Replication"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - jms_network

volumes:
  redis-data:
    driver_opts:
      type: local
      o: bind
      device: "/opt/redis/data"
  # redis-conf:
  #   driver_opts:
  #     type: local
  #     o: bind
  #     device: "/opt/redis/redis.conf"
  mariadb10-data:
    driver_opts:
      type: local
      o: bind
      device: "/opt/mariadb10/data"
  # mariadb10-conf:
  #   driver_opts:
  #     type: local
  #     o: bind
  #     device: "/opt/mariadb10/mariadb.cnf"
  # core-conf:
  #   driver_opts:
  #     type: local
  #     o: bind
  #     device: "/opt/jumpserver/core/config.yml"
  core-data:
    driver_opts:
      type: local
      o: bind
      device: "/opt/jumpserver/core/data"
  core-logs:
    driver_opts:
      type: local
      o: bind
      device: "/opt/jumpserver/core/logs"
  web-data:
    driver_opts:
      type: local
      o: bind
      device: "/opt/jumpserver/webui/data"
  web-logs:
    driver_opts:
      type: local
      o: bind
      device: "/opt/jumpserver/webui/logs"
  magnus-data:
    driver_opts:
      type: local
      o: bind
      device: "/opt/jumpserver/magnus"
  lion-data:
    driver_opts:
      type: local
      o: bind
      device: "/opt/jumpserver/lion"
  koko-data:
    driver_opts:
      type: local
      o: bind
      device: "/opt/jumpserver/koko"
  # koko-conf:
  #   driver_opts:
  #     type: local
  #     o: bind
  #     device: "/opt/jumpserver/koko/config.yml"

networks:
  jms_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: $DOCKER_SUBNET