---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-datadir-pv-1
  labels:
    name: zk-pv-1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.11.22
    path: /k8s/data/zk-1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-datadir-pv-2
  labels:
    name: zk-pv-2
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.11.22
    path: /k8s/data/zk-2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-datadir-pv-3
  labels:
    name: zk-pv-3
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.11.22
    path: /k8s/data/zk-3

