---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zk-pvc-1
  namespace: alpine-nginxport
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: zk-datadir-pv-1
  resources:
    requests:
      stroage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zk-pvc-2
  namespace: alpine-nginxport
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: zk-datadir-pv-2
  resources:
    requests:
      stroage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zk-pvc-2
  namespace: alpine-nginxport
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: zk-datadir-pv-3
  resources:
    requests:
      stroage: 1Gi

