apiVersion: v1
kind: Service
metadata:
  name: redis
  # 与 pod 名称空间保持一致
  namespace: hnp
spec:
  selector:
    app: redis
    role: logstorage
  clusterIP: 10.96.9.9
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379

