version: '3.7'
services:
  es01:
    # image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    build:
      context: .
      dockerfile: 7.17.1/Dockerfile
    container_name: es_single
    environment:
      - discovery.type=single-node
      - node.name=es_single
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=password
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    # chown 1000:1000
    volumes:
      - /opt/elasticsearch/es_log:/var/log
      - /opt/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
# 使用已有网络
networks:
   default:
     external:
       name: proxy
