version: '3'
services:
  jenkins:
    image: 'jenkins/jenkins:latest-jdk11'
    container_name: jenkins
    restart: always
    ports:
      - '8080:8080'
      - '50000:50000'
    # chown -R 1000:1000 /opt/jenkins
    volumes:
      - '/opt/jenkins:/var/jenkins_home'

